spring:
  application:
    name: document-service

  datasource:
    url: jdbc:postgresql://localhost:5437/document_db
    username: postgres
    password: postgres

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000