spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5437/document_db
    username: postgres
    password: postgres
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/